---
- name: Patch standalone ESXi host via API and save backup locally
  hosts: localhost
  gather_facts: no
  become: false
  vars:
    backup_file: /tmp/configBundle-esxi.host.domain.tgz

  tasks:
    - name: Confirm backup file was saved
      stat:
        path: '{{ backup_file }}'
      register: backup_file_info

    - name: Show backup status
      debug:
        msg: "Backup saved: {{ backup_file_info.stat.exists }}"
