---
- name: Patch standalone ESXi host via SSH
  hosts: ESXI-01
  gather_facts: no
  become: false
  vars:
    patch_file: /vmfs/volumes/VM_IMG_STORAGE/VMware-ESXi-7.0U3s-24585291-depot.zip

  tasks:
    - name: Put host in maintenance mode
      ansible.builtin.shell: vim-cmd hostsvc/maintenance_mode_enter
      register: enter_mm

    - name: Confirm maintenance mode entered
      debug: var=enter_mm.stdout

    - name: Install ESXi patch
      ansible.builtin.shell: >
        esxcli software vib install -d {{ patch_file }} --no-sig-check --force
      register: patch_output

    - name: Show patch result
      debug: var=patch_output.stdout_lines

    - name: Reboot ESXi host
      ansible.builtin.shell: reboot
      async: 1
      poll: 0

    - name: Wait for ESXi host to reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 600
        state: started

    - name: Exit maintenance mode
      ansible.builtin.shell: vim-cmd hostsvc/maintenance_mode_exit
      register: exit_mm

    - name: Confirm maintenance mode exited
      debug: var=exit_mm.stdout
